#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-panel &
sxhkd &
nm-applet &
picom & 

#$HOME/.screenlayout/resolucion.sh
#feh --bg-scale /path/to/image.file /path/to/image.file
#$HOME/.fehbg &
#$HOME/.config/polybar/launch.sh
picom --config ~/.config/picom/picom.conf &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV
#bspc monitor HDMI-0 -d I II 
#bspc monitor DVI-I-0 -d III IV
#bspc monitor HDMI-0 -s DVI-I-0
bspc desktop -f ^1

bspc config border_width         1
bspc config window_gap          5
bspc config -m primary top_padding 29
bspc config -m DVI-I-0 top_padding 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a firefox desktop='^3'
#bspc rule -a vlc state=floating

xsetroot -cursor_name left_ptr &


